name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar-cloud-scan:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Baixar Código-Fonte (Checkout)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Importante para o SonarCloud analisar o histórico

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Rodar Análise do SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token padrão do GitHub (não precisa criar)
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Esse você precisa atualizar no GitHub Secrets!
